//! Chain and token configuration traits.
//!
//! Implementations are generated by `#[derive(ChainConfig)]` and `#[derive(TokenConfig)]`
//! in `rig-wallet-macro`. See that crate's documentation for supported attributes.

pub use rig_wallet_macro::{ChainConfig, TokenConfig, evm_transfer_builder, tvm_transfer_builder};

use crate::{errors::Error, errors::Result};

/// Per-chain RPC endpoint and EVM chain ID.
///
/// Typically one config struct per network (e.g. `ETHConfig`, `SOLConfig`).
/// `RPC` / `CHAIN_ID` are selected at compile time via the `testnet` feature.
pub trait ChainConfig: Send + Sync + Clone {
    const RPC: &'static str;
    const CHAIN_ID: Option<u64>;

    fn chain_id() -> Result<u64> {
        Self::CHAIN_ID.ok_or_else(|| Error::Config("no chain ID configured".into()))
    }
}

/// Per-token mint / contract address and agent tool metadata.
///
/// Combined with a chain config as `ERC20Transfer<C, T>` or `SplTransfer<C, T>`.
/// `TOOL_NAME` must be unique across tokens registered on the same agent.
pub trait TokenConfig: Send + Sync + Clone {
    const TOKEN: &'static str;
    const DECIMAL: Option<u8>;
    /// Agent-visible tool name (e.g. `"ETHUSDC"`). Set via `#[tool_name = "..."]`.
    const TOOL_NAME: &'static str;
}
